module.exports = {
    ZERO_WIDTH: "\uFEFF",
	QUESTION: "?",
	DQUOTE: "\"",
	QUOTE: "'",
	GRAVE_ACCENT: "`",
	UNDER_SOURCE: "_",
	BSLASH: "\\",
	SLASH: "/",
	ASTERISK: "*",
	AT: "@",
	AND: "&",
	SHARP: "#",
	COMMA: ",",
	SEMICOLON: ";",
	COLON: ":",
	// LEFT_BRACKET: "{",
	// RIGHT_BRACKET: "}",
	// LEFT_SQUARE_BRACKET: "[",
	// RIGHT_SQUARE_BRACKET: "]",
	// LEFT_PARENTHE: "(",
	// RIGHT_PARENTHE: ")",
	POINT: ".",
	HYPHEN: "-",
	EQUALS: "=",
	TILDE: "~",
	EXCALMATORY: "!",
	// LEFT_ANGLE: "<",
	// RIGHT_ANGLE: ">"
};